; Generated by AutoGUI 2.6.2
#SingleInstance Force
#NoEnv
#include 4399UserTask.ahk
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

Gui Add, Text, x25 y20 w124 h25 +0x200, 任务选项

Gui Add, Text, vExecTime x25 y55 w210 h23 +0x200, 执行时间（如000001, 留空立即执行)：
Gui Add, Edit, vTimeStart x230 y55 w100 h21 +Number

Gui Add, CheckBox, visGFiance x25 y88 w50 h23, 融资
Gui Add, ComboBox, vFianceSeq xp+50 w30, 1|2|3|4|5

Gui Add, CheckBox, visPlayTurnTable xp+60 y88 w60 h23, 转盘x10
Gui Add, ComboBox, vTurnTableTimes xp+60 w30, 1|2|3|4|5|6|7
Gui Add, CheckBox, visHunter xp+50 w81 h23, 黑名单偷猎
Gui Add, CheckBox, visLand xp+90 w81 h23, 地产入驻

Gui Add, CheckBox, visGInjection x25 y+m w45 h23, 注资
Gui Add, ComboBox, vInjectionSeq xp+50 w30, 1|2|3
Gui Add, CheckBox, visBuy xp+60 yp+5 , 购买转盘


Gui Add, CheckBox, visCaiTuan x25 y+m w81 h23, 财团收钱
Gui Add, CheckBox, visShare xp+110 w88 h23, 分享20钻石
Gui Add, CheckBox, visCard xp+110 w82 h23, 刷拼图

Gui Add, ListView, vUlist x430 y25 w125 h303 gMyListView, UserTit|ID|Num
for key,num in numTable
        LV_Add("", key,idTable[key],num)


Gui Add, Text, cRed vTips x25 y262 w164 h23 +0x200,
Gui Add, CheckBox, visRecordingOn x25 y280 w81 h23, 开启录屏
Gui Add, Button, vBtnOpenLog x25 y304 w142 h23 gOpenLog, 查看当日log文件..
Gui Add, Button, vBtnCreateTask x16 y346 w115 h41 gCreateTask, 创建任务
Gui Add, Button, vBtnStopTask x138 y346 w108 h42 gReloading, 重置任务(F12)
Gui Add, Button, vBtnPauseTask x261 y348 w117 h40 gGuiPause, 暂停任务(F7恢复)
Gui Add, Button, vBtnClose x390 y348 w117 h40 gGuiClose, 关闭(F8)


GuiControl, Disable, BtnStopTask
GuiControl, Disable, BtnPauseTask
Gui Show, w588 h420, Tasks

Return


;ControlGet, SelectedItems, list, Selected,vLV

MyListView:
if (A_GuiEvent = "DoubleClick")
{
    LV_GetText(userName, A_EventInfo,1)  ; Get the text from the row's first field.
    LV_GetText(gameID, A_EventInfo,2)  ; Get the text from the row's first field.
    Launch4399GamePri(userName,gameID)
}
return

CreateTask:

    ;======================= Verification ========================================
    ControlGet, SelectedUsersC, List,Count Selected, SysListView321, Tasks
    if (SelectedUsersC < 1)
    {
        MsgBox, Please select at least one user!
        Return
    }

    GuiControlGet, isZhuZiSelected,, isGInjection
    GuiControlGet, zhuziWhich,, InjectionSeq
    if (isZhuZiSelected and zhuziWhich = "")
    {
        MsgBox, Please select a zhuzi sequence!
        Return
    }

    GuiControl, Disable, BtnCreateTask
    GuiControl, Enable, BtnStopTask
    GuiControl, Enable, BtnPauseTask
    GuiControl, Disable, TimeStart

    GuiControlGet, TimeStart 
    if !(TimeStart = "")
    {
        TimeNow := A_Hour A_Min A_Sec
        while !(TimeStart = TimeNow)
        {
            TimeNow := A_Hour A_Min A_Sec
            GuiControl,, Tips, % "执行倒计时：" . Floor(WaitTime(TimeStart)/60) . " 分 " . Round(mod(WaitTime(TimeStart),60),0) . " 秒"
            sleep 1000
        }
    }
    
    GuiControlGet, isRecordingOnSelected,, isRecordingOn        
    if isRecordingOnSelected
        GameRecordingOn()

    ControlGet, SelectedUsers, List,Selected, SysListView321, Tasks
    {
        Loop, Parse, SelectedUsers, `n  ; Rows are delimited by linefeeds (`n).
        {
            RowNumber := A_Index


            GuiControlGet, isCaiTuanSelected,, isCaiTuan
            GuiControlGet, isShareSelected,, isShare
            GuiControlGet, isHunterSelected,, isHunter            
            GuiControlGet, isZhuZiSelected,, isGInjection
            GuiControlGet, isRongZiSelected,, isGFiance
            GuiControlGet, visLandSelected,, isLand
            GuiControlGet, isBuySelected,, isBuy
            GuiControlGet, isCardSelected,, isCard






            U := StrSplit(A_LoopField, A_Tab)
            user := new 4399UserTask(U[1],0)

            if isCaiTuanSelected
                user.GetCaiTuan()

            if isShareSelected
                user.GetCard(3)

            if visLandSelected
                user.GetLand()

            if isHunterSelected
                user.Hunter(0)

            if isZhuZiSelected
                user.Zhuzi(zhuziWhich)

            if isRongZiSelected
                user.Rongzi(3)

            if isBuySelected
                user.GetCaiTuan()

            if isCardSelected
                user.GetCard()

            user := ""
            ;Loop, Parse, A_LoopField, %A_Tab%  ; Fields (columns) in each row are delimited by tabs (A_Tab).
            ;    MsgBox Row #%RowNumber% Col #%A_Index% is %A_LoopField%.
        }
    }

    if isRecordingOnSelected
        GameRecordingOff()

    GuiControl,, Tips,
    GuiControl,, TimeStart,
    GuiControl,Enable, TimeStart
    GuiControl,Enable, BtnCreateTask
    GuiControl,Disable, BtnStopTask
    GuiControl,Disable, BtnPauseTask
Return

OpenLog:
    FormatTime, Dayfolder,, yyyyMMdd        
    run % logPath . "\\" . Dayfolder .  "_log.txt"
return

GuiPause:
    Pause   
return

GuiEscape:
GuiClose:
    ExitApp

Reloading:
    Reload
return

F7::Pause   ;pause the script
F8::ExitApp ;stop the script
F12::Reload ;Reload the script
